In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [3]:
a = 56.7
b = 5L
a2 = 'a'
a3 = TRUE
a4 = 1+2i
class(a)
class(b)
class(a2)
class(a3)
class(a4)

[1] "numeric"

[1] "integer"

[1] "character"

[1] "logical"

[1] "complex"

In [15]:
x = c(1,2,3,4,5)
print(x)
x1 = list(1,2,3,4,5)
print(x1)
x2 = matrix(1:4,nrow = 2, ncol = 2)
print(x2)
x3 =c("East","West","East","North","North")#"East","West","West","West","East","North")
factorx3 = factor(x3)
print(factorx3)
data_frame = data.frame(x,x1,x3)
print(data_frame)
array_x = array(1:10)
print(array_x)

[1] 1 2 3 4 5
[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

     [,1] [,2]
[1,]    1    3
[2,]    2    4
[1] East  West  East  North North
Levels: East North West
  x X1 X2 X3 X4 X5    x3
1 1  1  2  3  4  5  East
2 2  1  2  3  4  5  West
3 3  1  2  3  4  5  East
4 4  1  2  3  4  5 North
5 5  1  2  3  4  5 North
 [1]  1  2  3  4  5  6  7  8  9 10

In [16]:
character(5)
integer(5)
numeric(5)
logical(5)
complex(5)

[1] "" "" "" "" ""

[1] 0 0 0 0 0

[1] 0 0 0 0 0

[1] FALSE FALSE FALSE FALSE FALSE

[1] 0+0i 0+0i 0+0i 0+0i 0+0i

In [20]:
c = c(1,2,3,4,5)
cnum = as.integer(c)
class(cnum)
print(cnum)
c1 = c(1L,2L,3L,4L,5L)
cnum1 = as.numeric(c1)
class(cnum1)
print(cnum1)
c2 = c('1','2','3')
cnum2 = as.numeric(c2)
class(cnum2)
print(cnum2)

[1] "integer"

[1] 1 2 3 4 5

[1] "numeric"

[1] 1 2 3 4 5

[1] "numeric"

[1] 1 2 3

In [23]:
a = 56.7
b = 5L
a2 = 'a'
a3 = TRUE
a4 = 1+2i
is.numeric(a)
is.integer(b)
is.character(a2)
is.logical(a3)
is.complex(a4)
x3 =c("East","West","East","North","North")
fact = factor(x3)
is.factor(fact)

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

In [26]:
x = c(1,2,3,4,5)
print(x[1:3])
x1 = list(1,2,3,4,5)
print(x1[1:3])
x2 = matrix(1:4,nrow = 2, ncol = 2)
print(x2[1,2])

[1] 1 2 3
[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[1] 3

In [35]:
x = c(1,2,3,4,5)
print(x[1:3])
x1 = list(1,2,3,4,5)
print(x1[1:3])
x2 = matrix(1:4,nrow = 2, ncol = 2)
print(x2[1,2])
x3 =c("East","West","East","North","North")
frame = data.frame(x,x3)
print(frame)
print(frame[1:2,])
x3 =c("East","West","East","North","North")
fact = factor(x3)
print(fact[1])

[1] 1 2 3
[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[1] 3
  x    x3
1 1  East
2 2  West
3 3  East
4 4 North
5 5 North
  x   x3
1 1 East
2 2 West
[1] East
Levels: East North West

In [37]:
x1 = list(1,2,3,4,5)
print(x1[3])
x2 = matrix(1:4,nrow = 2, ncol = 2)
print(x2[1,])
x3 =c("East","West","East","North","North")
frame = data.frame(x,x3)
print(frame[3,])

[[1]]
[1] 3

[1] 1 3
  x   x3
3 3 East

In [43]:
#Inserting new Column:
x3 =c("East","West","East","North","North")
frame = data.frame(x,x3)
frame$dept = c("a","b","d","c","e")
print(frame)
#Inserting Row:
x = c(4)
x3 = c("North")
dept = c("f")
frame1 = data.frame(x,x3,dept)
framefinal = rbind(frame, frame1)
print(framefinal)

  x    x3 dept
1 1  East    a
2 2  West    b
3 3  East    d
4 4 North    c
5 5 North    e
  x    x3 dept
1 1  East    a
2 2  West    b
3 3  East    d
4 4 North    c
5 5 North    e
6 4 North    f

In [48]:
x2 = matrix(1:4,nrow = 2, ncol = 2)
x22 = matrix(5:8,nrow = 2, ncol = 2)
res1 = x2+x22
res2 = x2-x22
res3 = x2*x22
res4 = x2/x22
print(res1)
print(res2)
print(res3)
print(res4)

     [,1] [,2]
[1,]    6   10
[2,]    8   12
     [,1] [,2]
[1,]   -4   -4
[2,]   -4   -4
     [,1] [,2]
[1,]    5   21
[2,]   12   32
          [,1]      [,2]
[1,] 0.2000000 0.4285714
[2,] 0.3333333 0.5000000

In [50]:
cbind(1:4)
rbind(1:4)

     [,1]
[1,] 1
[2,] 2
[3,] 3
[4,] 4

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4

In [ ]:
comb = function(n,)